site_name: More Greetings	
repo_url: https://github.com/systopia/de.systopia.moregreetings_de
site_description: 'Eine Anleitung für die More Greetings-Erweiterung.'
site_author: 'SYSTOPIA'
theme:
  name:
    material

nav:
  - Startseite: index.md
  - Grundlagen: basics.md
  - Installation: installation.md
  - Anwendung: usage.md
  - Beispiel: example.md

markdown_extensions:
  - attr_list
  - admonition
  - def_list
  - pymdownx.highlight:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tilde
  - pymdownx.betterem
  - pymdownx.mark

plugins:
  - search:
      lang: de
